-- PixelBattle: shared canvas, player profiles, history and server-side spending.

create table if not exists public.pixel_battle_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  username text not null,
  email text not null,
  balance integer not null default 30 check (balance between 0 and 100),
  placed_pixels integer not null default 0,
  best_streak integer not null default 0,
  active_days integer not null default 1,
  settings jsonb not null default '{}'::jsonb,
  last_recharge_at timestamptz not null default now(),
  last_login_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.canvas_pixels (
  x integer not null check (x >= 0 and x < 2000),
  y integer not null check (y >= 0 and y < 2000),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  user_id uuid not null references auth.users (id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key (x, y)
);

create table if not exists public.pixel_events (
  id bigint generated by default as identity primary key,
  x integer not null,
  y integer not null,
  color text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.pixel_rate_limits (
  user_id uuid primary key references auth.users (id) on delete cascade,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 0
);

alter table public.pixel_battle_profiles enable row level security;
alter table public.canvas_pixels enable row level security;
alter table public.pixel_events enable row level security;
alter table public.pixel_rate_limits enable row level security;

create policy "read own pixel battle profile"
  on public.pixel_battle_profiles for select
  using (auth.uid() = user_id);

create policy "read shared canvas pixels"
  on public.canvas_pixels for select
  using (true);

create policy "read shared pixel history"
  on public.pixel_events for select
  using (true);

create index if not exists canvas_pixels_xy_idx on public.canvas_pixels (x, y);
create index if not exists pixel_events_created_idx on public.pixel_events (created_at desc);
create index if not exists pixel_events_user_idx on public.pixel_events (user_id, created_at desc);

create or replace function public.create_pixel_battle_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  preferred_username text;
begin
  preferred_username := coalesce(
    nullif(new.raw_user_meta_data->>'username', ''),
    split_part(new.email, '@', 1),
    'player'
  );

  insert into public.pixel_battle_profiles (user_id, username, email)
  values (new.id, left(preferred_username, 24), coalesce(new.email, ''))
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists create_pixel_battle_profile_on_signup on auth.users;
create trigger create_pixel_battle_profile_on_signup
  after insert on auth.users
  for each row execute function public.create_pixel_battle_profile();

create or replace function public.get_pixel_battle_profile()
returns public.pixel_battle_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.pixel_battle_profiles;
  generated integer;
  new_balance integer;
begin
  if auth.uid() is null then
    raise exception 'auth_required';
  end if;

  insert into public.pixel_battle_profiles (user_id, username, email)
  values (
    auth.uid(),
    left(coalesce(nullif(auth.jwt()->>'email', ''), 'player'), 24),
    coalesce(auth.jwt()->>'email', '')
  )
  on conflict (user_id) do nothing;

  select * into current_profile
  from public.pixel_battle_profiles
  where user_id = auth.uid()
  for update;

  generated := greatest(0, floor(extract(epoch from (now() - current_profile.last_recharge_at)) / 2));
  new_balance := least(100, current_profile.balance + generated);

  if generated > 0 and new_balance <> current_profile.balance then
    update public.pixel_battle_profiles
    set balance = new_balance,
        last_recharge_at = case
          when new_balance = 100 then now()
          else current_profile.last_recharge_at + (generated * interval '2 seconds')
        end,
        last_login_at = now(),
        updated_at = now()
    where user_id = auth.uid()
    returning * into current_profile;
  else
    update public.pixel_battle_profiles
    set last_login_at = now(),
        updated_at = now()
    where user_id = auth.uid()
    returning * into current_profile;
  end if;

  return current_profile;
end;
$$;

create or replace function public.place_battle_pixel(pixel_x integer, pixel_y integer, pixel_color text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.pixel_battle_profiles;
  generated integer;
  new_balance integer;
  current_window timestamptz;
  current_attempts integer;
begin
  if auth.uid() is null then
    raise exception 'auth_required';
  end if;

  if pixel_x < 0 or pixel_x >= 2000 or pixel_y < 0 or pixel_y >= 2000 then
    raise exception 'bad_coordinates';
  end if;

  if pixel_color is null or pixel_color !~ '^#[0-9A-Fa-f]{6}$' then
    raise exception 'bad_color';
  end if;

  insert into public.pixel_rate_limits (user_id)
  values (auth.uid())
  on conflict (user_id) do nothing;

  select window_started_at, attempts
  into current_window, current_attempts
  from public.pixel_rate_limits
  where user_id = auth.uid()
  for update;

  if current_window < now() - interval '1 second' then
    update public.pixel_rate_limits
    set window_started_at = now(), attempts = 1
    where user_id = auth.uid();
  elsif current_attempts >= 8 then
    raise exception 'rate_limited';
  else
    update public.pixel_rate_limits
    set attempts = attempts + 1
    where user_id = auth.uid();
  end if;

  current_profile := public.get_pixel_battle_profile();

  if current_profile.balance <= 0 then
    raise exception 'no_pixels';
  end if;

  new_balance := current_profile.balance - 1;

  insert into public.canvas_pixels (x, y, color, user_id, updated_at)
  values (pixel_x, pixel_y, upper(pixel_color), auth.uid(), now())
  on conflict (x, y)
  do update set color = excluded.color,
                user_id = excluded.user_id,
                updated_at = excluded.updated_at;

  insert into public.pixel_events (x, y, color, user_id)
  values (pixel_x, pixel_y, upper(pixel_color), auth.uid());

  update public.pixel_battle_profiles
  set balance = new_balance,
      placed_pixels = placed_pixels + 1,
      best_streak = greatest(best_streak, placed_pixels + 1),
      last_recharge_at = now(),
      updated_at = now()
  where user_id = auth.uid()
  returning * into current_profile;

  return jsonb_build_object(
    'x', pixel_x,
    'y', pixel_y,
    'color', upper(pixel_color),
    'balance', current_profile.balance,
    'placedPixels', current_profile.placed_pixels
  );
end;
$$;

create or replace function public.get_pixel_battle_stats()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'canvasPixels', (select count(*) from public.canvas_pixels),
    'placedPixels', (select count(*) from public.pixel_events),
    'players', (select count(*) from public.pixel_battle_profiles),
    'myPixels', (
      select count(*)
      from public.pixel_events
      where user_id = auth.uid()
    )
  );
$$;

grant execute on function public.get_pixel_battle_profile() to authenticated;
grant execute on function public.place_battle_pixel(integer, integer, text) to authenticated;
grant execute on function public.get_pixel_battle_stats() to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.canvas_pixels;
exception
  when duplicate_object then null;
end;
$$;
